### ISSUE TITLE
Transferring new task subpackages into nipype GH org

### ISSUE THREAD

**Issue by tclose** [nipype/pydra-tasks-template#19]
I have created a new tasks subpackage `pydra-dcm2niix` in my [own GH account](http://github.com/tclose/pydra-dcm2niix), which I believe is ready for wider use (except I can't get the doctest to pass on GH because I'm not sure how to control the CWD).

Should it be transferred into the nipype org, and if so what should the process for doing this be?

**Comment by satra** [comment]
@tclose -we can add you as a member of nipype and you should be able to transfer it yourself.
