### ISSUE TITLE
[BUG] Installing from sdist fails with no such option 'subpackage'

### ISSUE THREAD

**Issue by tclose** [nipype/pydra-tasks-template#29]
When installing source distributions built from sub-packages created from this template there is an error in the preparing metadata phase. This error occurs for both pydra-fsl and pydra-dcm2niix so I'm assuming it is an issue with how the template is setup rather than the customisation of them.

```bash
$ pip install pydra-fsl/dist/pydra-fsl-0+untagged.121.g58a272c.tar.gz
Processing ./pydra-fsl/dist/pydra-fsl-0+untagged.121.g58a272c.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running dist_info
      error: error in setup.cfg: command 'egg_info' has no such option 'subpackage'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by effigies** [comment]
This definitely worked at some point, but either updates to pip or setuptools seem to have broken things. This is the line that's causing problems:

https://github.com/nipype/pydra-tasks-template/blob/03e1385e642af20651752da5e9e971f94aa04517/setup.cfg#L1-L2

The idea was to have a single place to change the value, but if it's going to break things, we're just going to need to replace `%(subpackage)s` with `TODO` everywhere and drop that section.

**Comment by tclose** [comment]
Since there are already a number of places where you need to do that it, I have just been using find/replace in any case so a couple more places won't hurt

**Comment by effigies** [comment]
Should no longer be an issue with flit.
